---
 - name: Create a new primary partition
   parted: 
     device: /dev/sdb
     number: 1
     state: present
     
 - name: Create a ext4 filesystem on /dev/sdb1
   filesystem:
     fstype: ext4
     dev : /dev/sdb1
