---
- name : Creating the users
  user: 
    name : "{{ name }}"
    password : "{{ 'Abc123' }} | password_hash{{ ('sha512') }}"
    shell : /bin/bash
    group : wheel
    groups : wheel
    home : /home/{{ name }} 
